import { LanguageModelRegistry } from '@theia/ai-core';
import { CodexProviderService } from '@cybervinci/ai-providers/lib/common/ai-providers-service';
import { FlowCreateWorkflowFromTemplateRequest, FlowCreateWorkflowFromPresetRequest, FlowCreateWorkflowFromPatternRequest, FlowCreateWorkflowFromAiAuthoringDraftRequest, FlowRunWorkflowPatternRequest, FlowPlanDynamicWorkflowRequest, FlowRunDynamicWorkflowRequest, FlowCreateAgentMarkdownRequest, FlowAgentMarkdownFile, FlowAgentMarkdownRequest, FlowAgentMarkdownSummary, FlowCleanupRunsRequest, FlowCleanupRunsResult, FlowDuplicateAgentMarkdownRequest, FlowExportRunRequest, FlowExportWorkflowRequest, FlowEffect, FlowEffectDecisionRequest, FlowRunExportResult, FlowWorkflowExportResult, FlowWorkflowVersion, FlowWorkflowVersionRequest, FlowGateDecisionRequest, FlowImportRunRequest, FlowImportWorkflowRequest, FlowMemoryWriteRequest, FlowPipelinePreset, FlowRun, FlowKernelRunMetadata, FlowRunLifecycleRequest, FlowRunRequest, FlowRunStreamRequest, FlowRunWorkspaceOptions, FlowRunWorkspaceState, FlowListPipelinePresetsRequest, FlowSaveModelProfileRequest, FlowSaveWorkflowRequest, FlowSavePipelinePresetRequest, FlowRenameAgentMarkdownRequest, FlowSecondRunApprovalRequest, FlowSecondRunDecisionRequest, FlowStartRunRequest, FlowClient, FlowCapabilities, FlowContextPack, FlowService, FlowSnapshot, FlowValidationResult, FlowWorkflow, FlowWorkflowFileRequest, FlowWorkflowRequest, FlowWorkflowTemplate, FlowWorkspaceRequest, FlowDynamicWorkflowPlan } from '../common';
import { FlowKernelBridge } from './flow-kernel-bridge';
import { AgentMarkdownStore } from './agent-markdown-store';
import { FlowStore } from './flow-store';
import { MarkdownWorkloadStore } from './markdown-workload-store';
import { MemoryAdapter } from './memory-adapter';
import { FileEffectHostAdapter } from './file-effect-host-adapter';
import { ImageEffectHostAdapter } from './image-effect-host-adapter';
import { FlowPlaybookRunner } from './flow-playbook-runner';
interface CodexProviderRuntimeReport {
    available: boolean;
    imageGeneration: boolean;
}
export declare class FlowServiceImpl implements FlowService {
    protected client?: FlowClient;
    protected readonly runStreams: any;
    protected readonly openingRunStreams: any;
    protected readonly store: FlowStore;
    protected readonly workloadStore: MarkdownWorkloadStore;
    protected readonly agentMarkdownStore: AgentMarkdownStore;
    protected readonly kernelBridge: FlowKernelBridge;
    protected readonly memory: MemoryAdapter;
    protected readonly fileEffectHostAdapter?: FileEffectHostAdapter;
    protected readonly imageEffectHostAdapter?: ImageEffectHostAdapter;
    protected readonly playbookRunner?: FlowPlaybookRunner;
    protected readonly languageModelRegistry?: LanguageModelRegistry;
    protected readonly codexProviderService?: CodexProviderService;
    setClient(client: FlowClient | undefined): void;
    dispose(): void;
    getCapabilities(): Promise<FlowCapabilities>;
    getAiAuthoringSpec(): Promise<import("../common").FlowAiAuthoringSpec>;
    getSnapshot(request: FlowWorkspaceRequest): Promise<FlowSnapshot>;
    listWorkflows(request: FlowWorkspaceRequest): Promise<FlowWorkflow[]>;
    listRuns(request: FlowWorkspaceRequest): Promise<FlowRun[]>;
    listWorkflowTemplates(): Promise<FlowWorkflowTemplate[]>;
    listWorkflowPatterns(): Promise<import("../common").FlowWorkflowPattern[]>;
    listModelProfiles(request?: FlowWorkspaceRequest): Promise<import("../common").FlowModelProfile[]>;
    saveModelProfile(request: FlowSaveModelProfileRequest): Promise<import("../common").FlowModelProfile>;
    listPipelinePresets(request: FlowListPipelinePresetsRequest): Promise<FlowPipelinePreset[]>;
    listAgentMarkdownFiles(request: FlowWorkspaceRequest): Promise<FlowAgentMarkdownSummary[]>;
    getAgentMarkdownFile(request: FlowAgentMarkdownRequest): Promise<FlowAgentMarkdownFile>;
    createAgentMarkdownFile(request: FlowCreateAgentMarkdownRequest): Promise<FlowAgentMarkdownFile>;
    duplicateAgentMarkdownFile(request: FlowDuplicateAgentMarkdownRequest): Promise<FlowAgentMarkdownFile>;
    renameAgentMarkdownFile(request: FlowRenameAgentMarkdownRequest): Promise<FlowAgentMarkdownFile>;
    createWorkflowFromTemplate(request: FlowCreateWorkflowFromTemplateRequest): Promise<FlowWorkflow>;
    createWorkflowFromPreset(request: FlowCreateWorkflowFromPresetRequest): Promise<FlowWorkflow>;
    createWorkflowFromPattern(request: FlowCreateWorkflowFromPatternRequest): Promise<FlowWorkflow>;
    createWorkflowFromAiAuthoringDraft(request: FlowCreateWorkflowFromAiAuthoringDraftRequest): Promise<FlowWorkflow>;
    runWorkflowPattern(request: FlowRunWorkflowPatternRequest): Promise<FlowRun>;
    planDynamicWorkflow(request: FlowPlanDynamicWorkflowRequest): Promise<FlowDynamicWorkflowPlan>;
    runDynamicWorkflow(request: FlowRunDynamicWorkflowRequest): Promise<FlowRun>;
    protected runAiAuthoringDraft(request: FlowRunDynamicWorkflowRequest): Promise<FlowRun>;
    protected recordDynamicWorkflowDecision(workspaceRootUri: string | undefined, run: FlowRun, plan: FlowDynamicWorkflowPlan, authoringAction?: string): Promise<FlowRun>;
    protected materializeAiAuthoringDraft(workspaceRootUri: string | undefined, draft: NonNullable<FlowRunDynamicWorkflowRequest['authoringDraft']>): Promise<FlowWorkflow>;
    savePipelinePreset(request: FlowSavePipelinePresetRequest): Promise<FlowPipelinePreset>;
    getWorkflow(request: FlowWorkflowRequest): Promise<FlowWorkflow>;
    openWorkflowFile(request: FlowWorkflowFileRequest): Promise<FlowWorkflow>;
    importWorkflow(request: FlowImportWorkflowRequest): Promise<FlowWorkflow>;
    exportWorkflow(request: FlowExportWorkflowRequest): Promise<FlowWorkflowExportResult>;
    exportRun(request: FlowExportRunRequest): Promise<FlowRunExportResult>;
    importRun(request: FlowImportRunRequest): Promise<FlowRun>;
    reloadWorkflow(request: FlowWorkflowRequest): Promise<FlowWorkflow>;
    saveWorkflow(request: FlowSaveWorkflowRequest): Promise<FlowValidationResult>;
    saveWorkflowFile(request: FlowSaveWorkflowRequest): Promise<FlowValidationResult>;
    listWorkflowVersions(request: FlowWorkflowRequest): Promise<FlowWorkflowVersion[]>;
    restoreWorkflowVersion(request: FlowWorkflowVersionRequest): Promise<FlowWorkflow>;
    validateWorkflow(workflow: FlowWorkflow): Promise<FlowValidationResult>;
    protected getPipelinePreset(workspaceRootUri: string | undefined, presetId: string): Promise<FlowPipelinePreset>;
    protected materializePresetAgents(workspaceRootUri: string | undefined, preset: FlowPipelinePreset): Promise<void>;
    protected materializeWorkflowAgents(workspaceRootUri: string | undefined, workflow: FlowWorkflow): Promise<void>;
    protected prepareRunWorkspace(workspaceRootUri: string | undefined, workflow: FlowWorkflow, options: FlowRunWorkspaceOptions | undefined): Promise<{
        workspaceRootUri?: string;
        workspace?: FlowRunWorkspaceState;
    }>;
    protected buildRunContextPack(workspaceRootUri: string | undefined, workflow: FlowWorkflow): Promise<FlowContextPack>;
    startRun(request: FlowStartRunRequest): Promise<FlowRun>;
    getRun(request: FlowRunRequest): Promise<FlowRun>;
    tickRun(request: FlowRunRequest): Promise<FlowRun>;
    pauseRun(request: FlowRunLifecycleRequest): Promise<FlowRun>;
    resumeRun(request: FlowRunLifecycleRequest): Promise<FlowRun>;
    cancelRun(request: FlowRunLifecycleRequest): Promise<FlowRun>;
    finalizeRun(request: FlowRunLifecycleRequest): Promise<FlowRun>;
    approveGate(request: FlowGateDecisionRequest): Promise<FlowRun>;
    cleanupRuns(request: FlowCleanupRunsRequest): Promise<FlowCleanupRunsResult>;
    decideEffect(request: FlowEffectDecisionRequest): Promise<FlowRun>;
    approveMemoryCandidate(request: FlowMemoryWriteRequest): Promise<FlowRun>;
    approveSecondRunSuggestion(request: FlowSecondRunApprovalRequest): Promise<FlowRun>;
    decideSecondRunSuggestion(request: FlowSecondRunDecisionRequest): Promise<FlowRun>;
    subscribeRunEvents(request: FlowRunStreamRequest): Promise<FlowRun>;
    unsubscribeRunEvents(request: FlowRunRequest): Promise<void>;
    protected updateRunLifecycle(request: FlowRunLifecycleRequest, update: (workflow: FlowWorkflow, run: FlowRun) => Promise<FlowRun>, streamAfterUpdate: boolean): Promise<FlowRun>;
    protected attachFinalReport(workspaceRootUri: string | undefined, run: FlowRun, note?: string): Promise<FlowRun>;
    protected ensureWorkflows(workspaceRootUri?: string): Promise<FlowWorkflow[]>;
    protected getRuntimeCapabilities(): Promise<FlowCapabilities>;
    protected resolveRunEventStreamCapability(): Promise<boolean>;
    protected resolvePlaybookExecutionCapability(): Promise<FlowCapabilities['playbookExecution']>;
    protected resolveLlmAgentProvider(codexProvider?: CodexProviderRuntimeReport): Promise<Pick<FlowCapabilities, 'llmAgentExecution' | 'llmAgentProvider' | 'demoMode'>>;
    protected resolveCodexProviderRuntimeReport(): Promise<CodexProviderRuntimeReport>;
    protected hasConfiguredAgentCommandProvider(): boolean;
    protected hasConfiguredTheiaLanguageModel(provider: string): Promise<boolean>;
    protected resolveFilesystemEditCapability(): {
        available: boolean;
    };
    protected hasConfiguredImageProvider(): boolean;
    protected isExplicitCodexProvider(): boolean;
    protected hasConfiguredCommandPolicy(): boolean;
    protected isDisabledEnv(name: string): boolean;
    protected resolveKernelBridgeMode(): Promise<'external' | 'simulated'>;
    protected resolveMemoryReport(): Promise<Awaited<ReturnType<MemoryAdapter['report']>>>;
    protected refreshRunFromKernel(workspaceRootUri: string | undefined, run: FlowRun): Promise<FlowRun>;
    protected legacyKernelMetadata(run: FlowRun): FlowKernelRunMetadata | undefined;
    protected isKernelBackedRun(run: FlowRun): boolean;
    protected ensureRunStream(request: FlowRunStreamRequest): void;
    protected openRunStream(request: FlowRunStreamRequest): Promise<void>;
    protected publishRunUpdate(workspaceRootUri: string | undefined, run: FlowRun, reason: Parameters<FlowClient['onRunUpdated']>[0]['reason']): void;
    protected recordEffectDecision(run: FlowRun, effect: FlowEffect, status: FlowEffect['status'], note?: string, approvedBy?: string): void;
    protected assertHostCapabilities(workflow: FlowWorkflow): Promise<void>;
}
export {};
