import { FlowWorkflow } from './flow-types';
import { FlowWorkflowPattern } from './flow-patterns';

export type FlowDynamicWorkflowDecisionKind = 'saved_workflow' | 'pattern' | 'generated_workflow';

export interface FlowDynamicWorkflowPlan {
    kind: FlowDynamicWorkflowDecisionKind;
    reason: string;
    workflowId?: string;
    patternId?: string;
    workflow?: FlowWorkflow;
    confidence: number;
    parameters?: Record<string, unknown>;
}

export interface FlowDynamicWorkflowPlanningInput {
    prompt: string;
    workflows: FlowWorkflow[];
    patterns: FlowWorkflowPattern[];
    preferSaved?: boolean;
}

export function planDynamicWorkflow(input: FlowDynamicWorkflowPlanningInput): FlowDynamicWorkflowPlan {
    const prompt = input.prompt.trim();
    if (input.preferSaved !== false) {
        const saved = chooseSavedWorkflow(prompt, input.workflows);
        if (saved) {
            return saved;
        }
    }
    const generated = chooseGeneratedWorkflow(prompt);
    if (generated) {
        return generated;
    }
    return choosePattern(prompt, input.patterns);
}

function chooseSavedWorkflow(prompt: string, workflows: FlowWorkflow[]): FlowDynamicWorkflowPlan | undefined {
    const promptTokens = tokenSet(prompt);
    if (promptTokens.size < 3) {
        return undefined;
    }
    const ranked = workflows
        .map(workflow => {
            const haystack = tokenSet([workflow.id, workflow.name, workflow.description, workflow.templateId].filter(Boolean).join(' '));
            const overlap = [...promptTokens].filter(token => haystack.has(token)).length;
            return { workflow, score: overlap / Math.max(1, Math.min(promptTokens.size, haystack.size)) };
        })
        .filter(item => item.score >= 0.28)
        .sort((left, right) => right.score - left.score);
    const winner = ranked[0];
    if (!winner) {
        return undefined;
    }
    return {
        kind: 'saved_workflow',
        workflowId: winner.workflow.id,
        reason: `Matched saved workflow "${winner.workflow.name}".`,
        confidence: Number(winner.score.toFixed(2))
    };
}

function choosePattern(prompt: string, patterns: FlowWorkflowPattern[]): FlowDynamicWorkflowPlan {
    const normalized = prompt.toLowerCase();
    const patternId = patternExists(patterns, 'simple_tournament') && /\b(tournament|torneio|compet|compare|comparar|melhor entre|winner|vencedor)\b/.test(normalized)
        ? 'simple_tournament'
        : patternExists(patterns, 'generate_and_filter') && /\b(alternativas|candidates|candidatos|ideias|opcoes|opções|escolha|filtrar|rank)\b/.test(normalized)
            ? 'generate_and_filter'
            : patternExists(patterns, 'adversarial_verification') && /\b(review|revis|critique|criticar|verificar|seguran|risco|audit|auditar)\b/.test(normalized)
                ? 'adversarial_verification'
                : patternExists(patterns, 'bounded_loop_until_done') && /\b(corrigir|repair|consertar|ate passar|até passar|loop|iterar|falha|debug)\b/.test(normalized)
                    ? 'bounded_loop_until_done'
                    : patternExists(patterns, 'fanout_and_synthesize_fixed') && /\b(paralel|fan.?out|varios|vários|cada arquivo|muitos arquivos|sintetizar)\b/.test(normalized)
                        ? 'fanout_and_synthesize_fixed'
                        : 'classify_and_act';
    return {
        kind: 'pattern',
        patternId,
        reason: `Selected pattern "${patternId}" from request shape.`,
        confidence: patternId === 'classify_and_act' ? 0.55 : 0.72,
        parameters: defaultDynamicParameters(patternId, prompt)
    };
}

function chooseGeneratedWorkflow(prompt: string): FlowDynamicWorkflowPlan | undefined {
    if (!isCreateNewWorkflowRequest(prompt)) {
        return undefined;
    }
    const id = sanitizeGeneratedWorkflowId(prompt);
    return {
        kind: 'generated_workflow',
        workflow: {
            version: 'flow.workflow/v1',
            id,
            name: generatedWorkflowName(prompt),
            description: 'Generated by CyberVinci dynamic workflow planning from the chat prompt.',
            requires: { capabilities: ['llm.agent.execute'] },
            agents: {
                planner: 'agents/dynamic/planner.md',
                executor: 'agents/dynamic/executor.md',
                verifier: 'agents/dynamic/verifier.md'
            },
            states: {
                input: { type: 'input', outputs: ['input/request.md'], outcomes: { success: 'planner' } },
                planner: {
                    type: 'agent',
                    agent: 'planner',
                    agentRole: 'planner',
                    modelExecution: {
                        profileId: 'balanced',
                        reasoningPolicy: 'auto',
                        virtualReasoning: { enabled: true, mode: 'balanced' }
                    },
                    systemPrompt: 'You are the planning stage for a dynamically generated CyberVinci Flow workflow.',
                    taskPrompt: 'Turn the user request into a concise execution plan and acceptance criteria.',
                    outputs: ['plan/plan.md', 'plan/acceptance-criteria.md'],
                    outcomes: { success: 'executor' }
                },
                executor: {
                    type: 'agent',
                    agent: 'executor',
                    agentRole: 'executor',
                    modelExecution: {
                        profileId: 'balanced',
                        reasoningPolicy: 'auto',
                        virtualReasoning: { enabled: true, mode: 'balanced' }
                    },
                    systemPrompt: 'You are the execution stage for a dynamically generated CyberVinci Flow workflow.',
                    taskPrompt: 'Execute the plan and produce the requested result without exposing internal reasoning.',
                    input: { include: ['input/request.md', 'plan/plan.md', 'plan/acceptance-criteria.md'] },
                    outputs: ['work/result.md'],
                    outcomes: { success: 'verifier' }
                },
                verifier: {
                    type: 'agent',
                    agent: 'verifier',
                    agentRole: 'verifier',
                    modelExecution: {
                        profileId: 'critical_judge',
                        reasoningPolicy: 'virtual',
                        virtualReasoning: { enabled: true, mode: 'balanced' }
                    },
                    systemPrompt: 'You are the verification stage for a dynamically generated CyberVinci Flow workflow.',
                    taskPrompt: 'Check the result against the original request and acceptance criteria. Return concise required fixes and approval status.',
                    input: { include: ['input/request.md', 'plan/acceptance-criteria.md', 'work/result.md'] },
                    outputs: ['verification/verification.md'],
                    outcomes: { success: 'final_report' }
                },
                final_report: {
                    type: 'report',
                    input: { include: ['plan/plan.md', 'plan/acceptance-criteria.md', 'work/result.md', 'verification/verification.md'] },
                    outputs: ['final/report.md']
                }
            },
            transitions: [
                { id: 'input_to_planner', from: 'input', to: 'planner', on: 'run.started' },
                { id: 'planner_to_executor', from: 'planner', to: 'executor', on: 'workload.completed' },
                { id: 'executor_to_verifier', from: 'executor', to: 'verifier', on: 'workload.completed' },
                { id: 'verifier_to_report', from: 'verifier', to: 'final_report', on: 'workload.completed' }
            ]
        },
        reason: 'Generated a new workflow because the request asks for a custom flow and no saved workflow matched.',
        confidence: 0.62
    };
}

function isCreateNewWorkflowRequest(prompt: string): boolean {
    const normalized = normalizeText(prompt);
    return /\b(crie|cria|criar|gere|gerar|monte|montar|construa|construir)\b.*\b(flow|workflow|pipeline|processo)\b/.test(normalized)
        || /\b(flow|workflow|pipeline|processo)\b.*\b(novo|nova|personalizado|personalizada|custom)\b/.test(normalized)
        || /\b(create|generate|build|make)\b.*\b(new|custom)?\s*(flow|workflow|pipeline)\b/.test(normalized)
        || /\b(new|custom)\b.*\b(flow|workflow|pipeline)\b/.test(normalized);
}

function defaultDynamicParameters(patternId: string, prompt: string): Record<string, unknown> {
    if (patternId === 'generate_and_filter') {
        return { candidateCount: prompt.length > 600 ? 5 : 3 };
    }
    if (patternId === 'simple_tournament') {
        return { competitorCount: prompt.length > 600 ? 4 : 3 };
    }
    if (patternId === 'bounded_loop_until_done') {
        return { maxIterations: /\b(deep|profundo|complex|difícil|dificil)\b/i.test(prompt) ? 4 : 3 };
    }
    return {};
}

function generatedWorkflowName(prompt: string): string {
    const tokens = [...tokenSet(prompt)].slice(0, 4);
    return tokens.length ? `Dynamic ${tokens.map(capitalize).join(' ')}` : 'Dynamic Workflow';
}

function sanitizeGeneratedWorkflowId(prompt: string): string {
    const tokens = [...tokenSet(prompt)].slice(0, 5);
    return `dynamic_${tokens.join('_') || 'workflow'}`.replace(/[^a-zA-Z0-9_-]+/g, '_').replace(/^_+|_+$/g, '').toLowerCase();
}

function capitalize(value: string): string {
    return value ? `${value.charAt(0).toUpperCase()}${value.slice(1)}` : value;
}

function patternExists(patterns: FlowWorkflowPattern[], patternId: string): boolean {
    return patterns.some(pattern => pattern.id === patternId);
}

function tokenSet(value: string): Set<string> {
    return new Set(normalizeText(value)
        .split(/[^a-z0-9_]+/g)
        .filter(token => token.length >= 3));
}

function normalizeText(value: string): string {
    return value
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '');
}
