[CmdletBinding()]
param(
    [string]$InstallDir = "$env:LOCALAPPDATA\Programs\CyberVinci",
    [switch]$NoWizard,
    [switch]$CreateDesktopShortcut,
    [switch]$CreateStartMenuShortcut
)

$ErrorActionPreference = 'Stop'

$payloadRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$profileRelativePath = "examples/electron/resources/cybervinci-install-profile.json"
$profilePath = Join-Path $payloadRoot $profileRelativePath

function Read-JsonFile([string]$Path) {
    return Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json
}

function Write-JsonFile([string]$Path, [object]$Value) {
    $parent = Split-Path -Parent $Path
    if (!(Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    $Value | ConvertTo-Json -Depth 100 | Set-Content -LiteralPath $Path -Encoding UTF8
}

function Get-ComponentState([object]$Profile, [string]$Id) {
    foreach ($component in $Profile.components) {
        if ($component.id -eq $Id) {
            return [bool]$component.selected
        }
    }
    return $false
}

function New-Shortcut([string]$ShortcutPath, [string]$TargetPath, [string]$WorkingDirectory, [string]$Arguments, [string]$IconPath) {
    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($ShortcutPath)
    $shortcut.TargetPath = $TargetPath
    $shortcut.Arguments = $Arguments
    $shortcut.WorkingDirectory = $WorkingDirectory
    $shortcut.IconLocation = $IconPath
    $shortcut.Save()
}

function Show-InstallWizard([object]$Profile, [string]$DefaultInstallDir) {
    try {
        Add-Type -AssemblyName System.Windows.Forms
        Add-Type -AssemblyName System.Drawing
    } catch {
        Write-Warning "Windows Forms is unavailable; using command-line defaults. $_"
        return $null
    }

    $form = New-Object System.Windows.Forms.Form
    $form.Text = "CyberVinci Setup"
    $form.StartPosition = 'CenterScreen'
    $form.Width = 700
    $form.Height = 430
    $form.FormBorderStyle = 'FixedDialog'
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false

    $title = New-Object System.Windows.Forms.Label
    $title.Text = "Install CyberVinci"
    $title.Font = New-Object System.Drawing.Font("Segoe UI", 16, [System.Drawing.FontStyle]::Bold)
    $title.Left = 24
    $title.Top = 20
    $title.Width = 620
    $title.Height = 32
    $form.Controls.Add($title)

    $desc = New-Object System.Windows.Forms.Label
    $desc.Text = "This wizard installs the CyberVinci payload generated by the release build. Optional Theia extensions are selected when the payload is built, then recorded here in the installed profile."
    $desc.Left = 24
    $desc.Top = 62
    $desc.Width = 620
    $desc.Height = 48
    $form.Controls.Add($desc)

    $installLabel = New-Object System.Windows.Forms.Label
    $installLabel.Text = "Install location"
    $installLabel.Left = 24
    $installLabel.Top = 124
    $installLabel.Width = 150
    $installLabel.Height = 22
    $form.Controls.Add($installLabel)

    $installBox = New-Object System.Windows.Forms.TextBox
    $installBox.Left = 180
    $installBox.Top = 122
    $installBox.Width = 430
    $installBox.Text = $DefaultInstallDir
    $form.Controls.Add($installBox)

    $components = New-Object System.Windows.Forms.GroupBox
    $components.Text = "Payload components"
    $components.Left = 24
    $components.Top = 165
    $components.Width = 630
    $components.Height = 112
    $form.Controls.Add($components)

    $core = New-Object System.Windows.Forms.CheckBox
    $core.Text = "CyberVinci Desktop core"
    $core.Left = 18
    $core.Top = 28
    $core.Width = 540
    $core.Checked = $true
    $core.Enabled = $false
    $components.Controls.Add($core)

    $csharp = New-Object System.Windows.Forms.CheckBox
    $csharp.Text = "C# and .NET tooling"
    $csharp.Left = 18
    $csharp.Top = 54
    $csharp.Width = 540
    $csharp.Checked = Get-ComponentState $Profile "csharp-dotnet"
    $csharp.Enabled = $false
    $components.Controls.Add($csharp)

    $codex = New-Object System.Windows.Forms.CheckBox
    $codex.Text = "Codex extension"
    $codex.Left = 18
    $codex.Top = 80
    $codex.Width = 540
    $codex.Checked = Get-ComponentState $Profile "codex-extension"
    $codex.Enabled = $false
    $components.Controls.Add($codex)

    $desktop = New-Object System.Windows.Forms.CheckBox
    $desktop.Text = "Create desktop shortcut"
    $desktop.Left = 42
    $desktop.Top = 295
    $desktop.Width = 240
    $desktop.Checked = $true
    $form.Controls.Add($desktop)

    $startMenu = New-Object System.Windows.Forms.CheckBox
    $startMenu.Text = "Create Start Menu shortcut"
    $startMenu.Left = 310
    $startMenu.Top = 295
    $startMenu.Width = 260
    $startMenu.Checked = $true
    $form.Controls.Add($startMenu)

    $ok = New-Object System.Windows.Forms.Button
    $ok.Text = "Install"
    $ok.Left = 478
    $ok.Top = 345
    $ok.Width = 84
    $ok.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $form.AcceptButton = $ok
    $form.Controls.Add($ok)

    $cancel = New-Object System.Windows.Forms.Button
    $cancel.Text = "Cancel"
    $cancel.Left = 570
    $cancel.Top = 345
    $cancel.Width = 84
    $cancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
    $form.CancelButton = $cancel
    $form.Controls.Add($cancel)

    $result = $form.ShowDialog()
    if ($result -ne [System.Windows.Forms.DialogResult]::OK) {
        throw "Installation canceled."
    }

    return @{
        InstallDir = $installBox.Text
        CreateDesktopShortcut = $desktop.Checked
        CreateStartMenuShortcut = $startMenu.Checked
    }
}

if (!(Test-Path -LiteralPath $profilePath)) {
    throw "CyberVinci install profile not found: $profilePath"
}

$profile = Read-JsonFile $profilePath

if (!$NoWizard) {
    $wizard = Show-InstallWizard $profile $InstallDir
    if ($wizard) {
        $InstallDir = $wizard.InstallDir
        $CreateDesktopShortcut = [switch]$wizard.CreateDesktopShortcut
        $CreateStartMenuShortcut = [switch]$wizard.CreateStartMenuShortcut
    }
}

$installFullPath = [System.IO.Path]::GetFullPath($InstallDir)
$payloadFullPath = [System.IO.Path]::GetFullPath($payloadRoot)
if ($installFullPath.StartsWith($payloadFullPath, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "InstallDir cannot be inside the payload directory."
}

New-Item -ItemType Directory -Force -Path $installFullPath | Out-Null
robocopy $payloadRoot $installFullPath /E /XD .git .codex-run .playwright-mcp /XF *.log *.tmp /NFL /NDL /NJH /NJS /NP | Out-Null
if ($LASTEXITCODE -gt 7) {
    throw "robocopy failed for $payloadRoot -> $installFullPath ($LASTEXITCODE)"
}

$installedProfile = Join-Path $installFullPath $profileRelativePath
Write-JsonFile $installedProfile $profile

$launcher = Join-Path $installFullPath "CyberVinci.vbs"
if (!(Test-Path -LiteralPath $launcher)) {
    throw "Installed launcher not found: $launcher"
}
$wscript = Join-Path $env:WINDIR "System32\wscript.exe"
$icon = Join-Path $installFullPath "resources\cybervinci.ico"
if (!(Test-Path -LiteralPath $icon)) {
    $icon = Join-Path $installFullPath "node_modules\electron\dist\electron.exe"
}

if ($CreateDesktopShortcut) {
    $desktopDir = [Environment]::GetFolderPath('Desktop')
    New-Shortcut (Join-Path $desktopDir "CyberVinci.lnk") $wscript $installFullPath "`"$launcher`"" $icon
}

if ($CreateStartMenuShortcut) {
    $programsDir = [Environment]::GetFolderPath('Programs')
    $startMenuDir = Join-Path $programsDir "CyberVinci"
    New-Item -ItemType Directory -Force -Path $startMenuDir | Out-Null
    New-Shortcut (Join-Path $startMenuDir "CyberVinci.lnk") $wscript $installFullPath "`"$launcher`"" $icon
}

Write-Host "CyberVinci installed at $installFullPath" -ForegroundColor Green
Write-Host "Launcher: $launcher"
