import { expect } from 'chai';
import { createBuilderDocument, type BuilderDocument } from '@cybervinci/builder-schema';
import { BuilderReactExportError, generateBuilderPageTsx, reactExporter } from './index';

describe('builder reactExporter', () => {

    it('exports TSX from the canonical Builder document and includes the document JSON', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'landing', title: 'Landing' }),
            tree: {
                id: 'page',
                type: 'Page',
                props: { title: 'Landing' },
                children: [
                    {
                        id: 'hero',
                        type: 'HeroSection',
                        props: {
                            title: 'Build interfaces',
                            subtitle: 'Builder stays canonical.'
                        },
                        slots: {
                            actions: [
                                {
                                    id: 'cta',
                                    type: 'Button',
                                    props: { children: 'Start' }
                                }
                            ]
                        }
                    },
                    {
                        id: 'content',
                        type: 'Container',
                        children: [
                            {
                                id: 'copy',
                                type: 'Text',
                                props: { children: 'Generated TSX is an export artifact.' }
                            }
                        ]
                    }
                ]
            }
        };

        const result = reactExporter(document);
        const tsx = result.files['Page.tsx'];

        expect(tsx).to.contain('Generated from Builder Schema');
        expect(tsx).to.contain('Do not edit this file as the canonical source');
        expect(tsx).to.contain("import type * as React from 'react';");
        expect(tsx).to.contain('import { Box, Button, Container, MantineProvider, Text } from "@mantine/core";');
        expect(tsx).to.contain('function BuilderHeroSection');
        expect(tsx).to.contain('<BuilderHeroSection');
        expect(tsx).to.contain('data-builder-type="HeroSection"');
        expect(tsx).to.contain('title="Build interfaces"');
        expect(tsx).to.contain('{/* Builder slot: actions */}');
        expect(tsx).to.contain('<Button');
        expect(tsx).to.contain('{\"Start\"}');
        expect(tsx).to.contain('<Container');
        expect(result.files['builder-document.json']).to.contain('"schemaVersion"');
        expect(result.files['builder-document.json']).to.contain('"HeroSection"');
        expect(result.warnings).to.deep.equal([]);
    });

    it('optionally emits schema.json next to the generated TSX for Builder traceability', () => {
        const document = createBuilderDocument({ id: 'traceable', title: 'Traceable' });

        const result = reactExporter(document, { includeSchemaJson: true });

        expect(result.files['Page.tsx']).to.contain('Generated from Builder Schema');
        expect(result.files['schema.json']).to.equal(result.files['builder-document.json']);
        expect(result.files['schema.json']).to.contain('"schemaVersion"');
        expect(result.files['schema.json']).to.contain('"Traceable"');
    });

    it('does not emit schema.json unless requested', () => {
        const document = createBuilderDocument({ id: 'default', title: 'Default' });

        const result = reactExporter(document);

        expect(result.files['schema.json']).to.equal(undefined);
    });

    it('rejects invalid documents by default', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'invalid', title: 'Invalid' }),
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'unknown',
                        type: 'UnknownPremiumWidget'
                    }
                ]
            }
        };

        expect(() => reactExporter(document)).to.throw(BuilderReactExportError);
    });

    it('rejects invalid or forbidden URL props during validated React export', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'bad-url', title: 'Bad URL' }),
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'link',
                        type: 'Anchor',
                        props: { children: 'Run', href: 'javascript:alert(1)' }
                    }
                ]
            }
        };

        expect(() => reactExporter(document)).to.throw(BuilderReactExportError, 'Cannot export invalid Builder document to React/TSX.');
    });

    it('omits unsafe URL props from React export when validation is disabled', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'unsafe-url-export', title: 'Unsafe URL Export' }),
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'link',
                        type: 'Anchor',
                        props: { children: 'Run', href: 'javascript:alert(1)' }
                    },
                    {
                        id: 'image',
                        type: 'Image',
                        props: { src: 'data:text/html,<script>alert(1)</script>', alt: 'Preview' }
                    }
                ]
            }
        };

        const result = reactExporter(document, { validate: false, includeCanonicalDocument: false });
        const tsx = result.files['Page.tsx'];

        expect(tsx).to.contain('<Anchor');
        expect(tsx).to.contain('<Image');
        expect(tsx).not.to.contain('href=');
        expect(tsx).not.to.contain('src=');
        expect(tsx).not.to.contain('javascript:');
        expect(tsx).not.to.contain('data:text/html');
        expect(result.warnings.map(warning => warning.path)).to.include.members([
            'node(link).props.href',
            'node(image).props.src'
        ]);
    });

    it('emits a friendly fallback for unknown components when validation is disabled', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'fallback', title: 'Fallback' }),
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'unknown',
                        type: 'UnknownPremiumWidget',
                        props: {
                            children: 'Premium content',
                            onClick: 'alert(1)',
                            dangerouslySetInnerHTML: '<script>alert(1)</script>'
                        }
                    }
                ]
            }
        };

        const result = reactExporter(document, { validate: false, includeCanonicalDocument: false });
        const tsx = result.files['Page.tsx'];

        expect(tsx).to.contain('function BuilderUnsupported');
        expect(tsx).to.contain('<BuilderUnsupported');
        expect(tsx).to.contain('componentType="UnknownPremiumWidget"');
        expect(tsx).to.contain('{\"Premium content\"}');
        expect(tsx).not.to.contain('dangerouslySetInnerHTML');
        expect(tsx).not.to.contain('onClick');
        expect(result.files['builder-document.json']).to.equal(undefined);
        expect(result.warnings).to.have.length(1);
        expect(result.warnings[0].nodeId).to.equal('unknown');
    });

    it('generates Page.tsx directly with only the Mantine imports used by the tree', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'form', title: 'Form' }),
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'stack',
                        type: 'Stack',
                        props: { gap: 'md' },
                        children: [
                            {
                                id: 'title',
                                type: 'Title',
                                props: { order: 2, children: 'Contact' }
                            },
                            {
                                id: 'email',
                                type: 'TextInput',
                                props: { label: 'Email', placeholder: 'you@example.com' }
                            },
                            {
                                id: 'submit',
                                type: 'Button',
                                props: { children: 'Send' }
                            }
                        ]
                    }
                ]
            }
        };

        const tsx = generateBuilderPageTsx(document);

        expect(tsx).to.contain('import { Box, Button, MantineProvider, Stack, TextInput, Title } from "@mantine/core";');
        expect(tsx).to.contain('<Stack');
        expect(tsx).to.contain('gap="md"');
        expect(tsx).to.contain('<TextInput');
        expect(tsx).to.contain('label="Email"');
        expect(tsx).not.to.contain('Container');
    });

    it('emits action stubs and binds Builder events without using JSX as the canonical source', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'actions', title: 'Actions' }),
            actions: {
                submitLead: {
                    type: 'submitForm',
                    params: { formId: 'lead-form' }
                },
                'open-details': {
                    type: 'openModal',
                    params: { modalId: 'details' }
                }
            },
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'submit',
                        type: 'Button',
                        props: { children: 'Submit' },
                        events: {
                            onClick: {
                                actionId: 'submitLead',
                                preventDefault: true,
                                params: { source: 'hero' }
                            }
                        }
                    },
                    {
                        id: 'details',
                        type: 'Button',
                        props: { children: 'Details' },
                        events: {
                            onClick: {
                                actionId: 'open-details',
                                stopPropagation: true
                            }
                        }
                    }
                ]
            }
        };

        const result = reactExporter(document);
        const tsx = result.files['Page.tsx'];
        const canonicalJson = result.files['builder-document.json'];

        expect(tsx).to.contain('const builderActions = {');
        expect(tsx).to.contain('submitLead: async (event?: unknown, binding?: Record<string, unknown>)');
        expect(tsx).to.contain('open_details: async (event?: unknown, binding?: Record<string, unknown>)');
        expect(tsx).to.contain('onClick={(event) => builderActions.submitLead(event, {');
        expect(tsx).to.contain('"preventDefault": true');
        expect(tsx).to.contain('onClick={(event) => builderActions.open_details(event, {');
        expect(tsx).to.contain('"stopPropagation": true');
        expect(canonicalJson).to.contain('"actions"');
        expect(canonicalJson).to.contain('"events"');
        expect(canonicalJson).not.to.contain('onClick={(event)');
        expect(canonicalJson).not.to.contain('<Button');
    });

    it('emits data service stubs for bound data sources while preserving Builder JSON as source of truth', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'dashboard', title: 'Dashboard' }),
            dataSources: {
                metrics: {
                    type: 'static',
                    config: {
                        data: [
                            { label: 'Revenue', value: 42 },
                            { label: 'Users', value: 150 }
                        ]
                    }
                },
                profile: {
                    type: 'mock',
                    config: {
                        data: { name: 'Ada' }
                    }
                }
            },
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'metric-grid',
                        type: 'MetricGrid',
                        data: {
                            repeat: {
                                sourceId: 'metrics',
                                itemName: 'metric'
                            }
                        }
                    },
                    {
                        id: 'profile-name',
                        type: 'Text',
                        data: {
                            sourceId: 'profile',
                            path: 'name'
                        },
                        props: { children: 'Profile' }
                    }
                ]
            }
        };

        const result = reactExporter(document);
        const tsx = result.files['Page.tsx'];

        expect(tsx).to.contain('const builderDataServices = {');
        expect(tsx).to.contain("Builder data service stub for 'metrics' (static).");
        expect(tsx).to.contain("Builder data service stub for 'profile' (mock).");
        expect(tsx).to.contain('metrics: async () => {');
        expect(tsx).to.contain('profile: async () => {');
        expect(result.files['builder-document.json']).to.contain('"dataSources"');
        expect(result.files['builder-document.json']).to.contain('"MetricGrid"');
        expect(result.files['builder-document.json']).not.to.contain('builderDataServices');
    });

    it('optionally extracts large top-level sections into separate component files', () => {
        const document: BuilderDocument = {
            ...createBuilderDocument({ id: 'landing', title: 'Landing' }),
            tree: {
                id: 'page',
                type: 'Page',
                children: [
                    {
                        id: 'hero',
                        type: 'HeroSection',
                        props: {
                            title: 'Build interfaces',
                            subtitle: 'Builder stays canonical.'
                        },
                        slots: {
                            actions: [
                                {
                                    id: 'primary',
                                    type: 'Button',
                                    props: { children: 'Start' }
                                },
                                {
                                    id: 'secondary',
                                    type: 'Button',
                                    props: { children: 'Docs' }
                                }
                            ]
                        },
                        children: [
                            {
                                id: 'hero-note',
                                type: 'Text',
                                props: { children: 'Exported as its own component.' }
                            }
                        ]
                    },
                    {
                        id: 'small',
                        type: 'Section',
                        children: [
                            {
                                id: 'small-copy',
                                type: 'Text',
                                props: { children: 'Small sections stay inline.' }
                            }
                        ]
                    }
                ]
            }
        };

        const result = reactExporter(document, {
            separateLargeSections: true,
            largeSectionNodeThreshold: 4,
            includeCanonicalDocument: false
        });

        expect(result.files['Page.tsx']).to.contain("import { HeroSection } from './components/HeroSection';");
        expect(result.files['Page.tsx']).to.contain('<HeroSection />');
        expect(result.files['Page.tsx']).to.contain('data-builder-type="Section"');
        expect(result.files['Page.tsx']).to.contain('id="small"');
        expect(result.files['components/HeroSection.tsx']).to.contain('export function HeroSection(): JSX.Element');
        expect(result.files['components/HeroSection.tsx']).to.contain('<BuilderHeroSection');
        expect(result.files['components/HeroSection.tsx']).to.contain('<Button');
        expect(result.files['components/HeroSection.tsx']).to.contain('Exported as its own component.');
    });
});
