import { FlowAiAuthoringDraft, FlowService, FlowWorkflow } from '@cybervinci/flow/lib/common';
import { MemoryItem, MemoryScope, MemoryService } from '@cybervinci/memory/lib/common';
import { CyberVinciAiExecutionSelection, CyberVinciAiProviderDescriptor } from '@cybervinci/ai-runtime/lib/common';
import { CyberVinciAiRuntimeFrontendService } from '@cybervinci/ai-runtime/lib/browser/ai-runtime-frontend-service';
import { CodexProviderInputItem } from '@cybervinci/ai-providers/lib/common';
import { ChatAgent, ChatAgentService, MutableChatRequestModel } from '@theia/ai-chat/lib/common';
import { ToolInvocationContext, ToolInvocationRegistry, ToolRequest } from '@theia/ai-core';
import { MCPFrontendService, MCPServerDescription } from '@theia/ai-mcp/lib/common/mcp-server-manager';
import { OpenPencilApplyOperationsOptions, OpenPencilDesignCommandService, OpenPencilDesignSession } from '@cybervinci/openpencil-extension/lib/browser/openpencil-design-command-service';
import { OpenPencilDesignOperation, OpenPencilDocument, OpenPencilNode, OpenPencilPage, OpenPencilValidationIssue } from '@cybervinci/openpencil-extension/lib/common/openpencil-types';
import { ApplicationShell } from '@theia/core/lib/browser';
import { CommandService, ILogger } from '@theia/core';
import { QuickPickService } from '@theia/core/lib/common/quick-pick-service';
import { PreferenceService } from '@theia/core/lib/common/preferences';
import URI from '@theia/core/lib/common/uri';
import { WorkspaceService } from '@theia/workspace/lib/browser';
import { CyberVinciAgentDefinition, CyberVinciAgentCapabilityProfile, CyberVinciAgentPromptCapability, CyberVinciAgentToolCapability, CyberVinciAgentVariableCapability, CyberVinciAiChatExperienceService, CyberVinciHostToolExecutionContext, CyberVinciHostToolExecutionResult, CyberVinciPlaybookDefinition, CyberVinciToolDefinition } from '../common';
interface CyberVinciCanvasDiagnostic {
    category: 'document' | 'overlap' | 'off-canvas' | 'text-overflow' | 'footer' | 'clone-completeness' | 'layout-quality';
    severity: 'info' | 'warning' | 'error';
    message: string;
    nodeId?: string;
    otherNodeId?: string;
    details?: Record<string, unknown>;
}
interface CyberVinciCanvasNodeBox {
    id: string;
    name?: string;
    type: string;
    x: number;
    y: number;
    width: number;
    height: number;
    parentId?: string;
    depth: number;
    text?: string;
}
interface CyberVinciNativeMcpServerGroup {
    id: string;
    label: string;
    default?: boolean;
    requiresUserSecret?: boolean;
    promptVariantId?: string;
    promptRefs?: string[];
    servers: MCPServerDescription[];
}
interface CyberVinciNativeMcpRequirement {
    agentId: string;
    agentName: string;
    sourceAgentId?: string;
    groups: CyberVinciNativeMcpServerGroup[];
}
interface CyberVinciMcpServerStatus {
    name: string;
    configured: boolean;
    started: boolean;
    hasPlaceholderSecret?: boolean;
}
interface FlowWorkflowSummaryForAi {
    id: string;
    name: string;
    description?: string;
    stateCount: number;
    transitionCount: number;
    editable: boolean;
}
type CyberVinciPlaybookToolRunner = (playbookId: string, context: CyberVinciHostToolExecutionContext) => Promise<CyberVinciHostToolExecutionResult>;
type CyberVinciPlaybookToolResumer = (requestId: string, context: CyberVinciHostToolExecutionContext) => Promise<CyberVinciHostToolExecutionResult>;
export declare class CyberVinciToolRegistry {
    protected readonly service: CyberVinciAiChatExperienceService;
    protected readonly commandService: CommandService;
    protected readonly preferenceService: PreferenceService;
    protected readonly logger: ILogger;
    protected readonly flowService: FlowService | undefined;
    protected readonly memoryService: MemoryService | undefined;
    protected readonly aiRuntime: CyberVinciAiRuntimeFrontendService | undefined;
    protected readonly toolInvocationRegistry: ToolInvocationRegistry | undefined;
    protected readonly chatAgentService: ChatAgentService | undefined;
    protected readonly mcpService: MCPFrontendService | undefined;
    protected readonly openPencilDesignCommandService: OpenPencilDesignCommandService | undefined;
    protected readonly shell: ApplicationShell | undefined;
    protected readonly workspaceService: WorkspaceService | undefined;
    protected readonly quickPickService: QuickPickService | undefined;
    protected toolsById: Map<string, CyberVinciToolDefinition> | undefined;
    protected playbookRunner: CyberVinciPlaybookToolRunner | undefined;
    protected playbookResumer: CyberVinciPlaybookToolResumer | undefined;
    setPlaybookRunner(runner: CyberVinciPlaybookToolRunner): void;
    setPlaybookResumer(resumer: CyberVinciPlaybookToolResumer): void;
    getTool(id: string): Promise<CyberVinciToolDefinition | undefined>;
    executeTool(toolId: string, context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected getToolsById(): Promise<Map<string, CyberVinciToolDefinition>>;
    protected executeHostTool(toolId: string, context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected describeAgent(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected agentMigrationStatus(agent: CyberVinciAgentDefinition, capabilityProfile: CyberVinciAgentCapabilityProfile, playbookId: string, runtimeAgent: ChatAgent | undefined): Record<string, unknown>;
    protected preflightAgent(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected resolvePreflightPlaybook(playbookId: string): Promise<{
        playbook?: CyberVinciPlaybookDefinition;
        generated: boolean;
        fallbackPlaybookId?: string;
    }>;
    protected createRuntimeAutonomousPlaybook(playbookId: string): CyberVinciPlaybookDefinition;
    protected nativeAgentMcpRequirements(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected nativeMcpRequirementForAgent(agent: CyberVinciAgentDefinition | undefined, capabilityProfile: CyberVinciAgentCapabilityProfile, context: CyberVinciHostToolExecutionContext): CyberVinciNativeMcpRequirement | undefined;
    protected nativeMcpRequirementGroupForPromptRef(promptRef: string): CyberVinciNativeMcpServerGroup | undefined;
    protected githubMcpRequirementGroup(): CyberVinciNativeMcpServerGroup;
    protected chromeDevToolsMcpRequirementGroup(): CyberVinciNativeMcpServerGroup;
    protected playwrightMcpRequirementGroup(): CyberVinciNativeMcpServerGroup;
    protected selectNativeMcpRequirementGroup(groups: CyberVinciNativeMcpServerGroup[], context: CyberVinciHostToolExecutionContext): CyberVinciNativeMcpServerGroup;
    protected readMcpRequirementStatuses(servers: MCPServerDescription[]): Promise<CyberVinciMcpServerStatus[]>;
    protected isPlaceholderMcpSecret(value: string | undefined): boolean;
    protected openMcpSettingsPreference(): Promise<void>;
    protected providerStatus(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected respondInChat(context: CyberVinciHostToolExecutionContext): CyberVinciHostToolExecutionResult;
    protected resolveAgentFromContext(agents: CyberVinciAgentDefinition[], context: CyberVinciHostToolExecutionContext): CyberVinciAgentDefinition | undefined;
    protected contextAgentHints(context: CyberVinciHostToolExecutionContext): string[];
    protected expectsAgentInContext(context: CyberVinciHostToolExecutionContext): boolean;
    protected resolveRuntimeChatAgent(agent: CyberVinciAgentDefinition | undefined, context: CyberVinciHostToolExecutionContext): ChatAgent | undefined;
    protected agentIdFromNativePlaybook(playbookId: string | undefined): string | undefined;
    protected toRuntimeNativeAgentDefinition(agent: ChatAgent): CyberVinciAgentDefinition;
    protected nativeAgentPlaybookId(agentId: string): string;
    protected agentCapabilityProfile(agent: CyberVinciAgentDefinition, runtimeProfile?: CyberVinciAgentCapabilityProfile): CyberVinciAgentCapabilityProfile;
    protected runtimeAgentCapabilityProfile(agent: ChatAgent | undefined): CyberVinciAgentCapabilityProfile;
    protected functionToolCapabilities(functionIds: readonly string[], source: CyberVinciAgentToolCapability['source']): CyberVinciAgentToolCapability[];
    protected runtimeAgentSummary(agent: ChatAgent | undefined): Record<string, unknown>;
    protected runtimePromptSets(agent: ChatAgent): CyberVinciAgentPromptCapability[];
    protected runtimePromptFunctionRefs(agent: ChatAgent): string[];
    protected runtimeMcpPromptRefs(agent: ChatAgent): string[];
    protected extractPromptFunctionRefs(template: string | undefined): string[];
    protected extractMcpPromptRefs(template: string | undefined): string[];
    protected runtimeAgentSpecificVariables(agent: ChatAgent): CyberVinciAgentVariableCapability[];
    protected promptFragmentId(fragment: {
        id?: string;
    } | undefined): string | undefined;
    protected languageModelRequirementLabel(requirement: unknown): string;
    protected functionBridgeStatus(functionIds: readonly string[] | undefined): {
        available: boolean;
        toolCount: number;
        declaredFunctions: string[];
        registeredFunctions: string[];
        missingFunctions: string[];
        functions: Array<{
            id: string;
            registered: boolean;
            name?: string;
            providerName?: string;
        }>;
    };
    protected mergeAgentCapabilityProfiles(...profiles: CyberVinciAgentCapabilityProfile[]): CyberVinciAgentCapabilityProfile;
    protected mergeToolCapabilities(...groups: CyberVinciAgentToolCapability[][]): CyberVinciAgentToolCapability[];
    protected mergeVariableCapabilities(...groups: CyberVinciAgentVariableCapability[][]): CyberVinciAgentVariableCapability[];
    protected mergePromptCapabilities(...groups: CyberVinciAgentPromptCapability[][]): CyberVinciAgentPromptCapability[];
    protected uniqueStrings(values: readonly unknown[]): string[];
    protected listPlaybooks(): Promise<CyberVinciHostToolExecutionResult>;
    protected runPlaybookTool(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected resumePlaybookTool(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected compilePlaybookToFlowDraft(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected createFlowFromPlaybook(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected executeCommandTool(toolId: string, context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected executeCompositeTool(tool: CyberVinciToolDefinition, context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected executeTheiaTool(toolId: string, context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected listTheiaTools(): CyberVinciHostToolExecutionResult;
    protected readTheiaToolArgs(context: CyberVinciHostToolExecutionContext): string;
    protected createTheiaToolContext(context: CyberVinciHostToolExecutionContext, tool: ToolRequest): ToolInvocationContext;
    protected asChatRequest(candidate: unknown): MutableChatRequestModel | undefined;
    protected hasToolCallError(result: unknown): boolean;
    protected stringifyToolResult(result: unknown): string;
    protected setPreference(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected listFlowWorkflows(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected listPendingFlowGates(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected approveFlowGate(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected startFlowRun(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected runDynamicWorkflow(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected runAiAuthoringDraft(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected runAiAuthoredDynamicWorkflow(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected createWorkflowFromAiAuthoringDraft(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected getFlowAiAuthoringSpec(): Promise<CyberVinciHostToolExecutionResult>;
    protected searchMemoryContext(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected proposeMemoryCandidate(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected requestMemoryWriteApproval(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected writeApprovedMemory(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected mcpHasServer(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected mcpIsServerStarted(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected mcpConfigureServers(context: CyberVinciHostToolExecutionContext, start: boolean): Promise<CyberVinciHostToolExecutionResult>;
    protected readMcpServerName(context: CyberVinciHostToolExecutionContext): string;
    protected readMcpServers(context: CyberVinciHostToolExecutionContext): MCPServerDescription[];
    protected captureCanvasDocument(context: CyberVinciHostToolExecutionContext): CyberVinciHostToolExecutionResult;
    protected captureCanvasVisualSnapshot(context: CyberVinciHostToolExecutionContext): CyberVinciHostToolExecutionResult;
    protected collectCanvasLayoutDiagnostics(context: CyberVinciHostToolExecutionContext, categories?: CyberVinciCanvasDiagnostic['category'][]): CyberVinciHostToolExecutionResult;
    protected applyCanvasOperations(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected resizeCanvasNodesToFit(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected reorderCanvasLayers(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected getCanvasKnownSiteReference(context: CyberVinciHostToolExecutionContext): CyberVinciHostToolExecutionResult;
    protected runVisionJudge(context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected runDeterministicVisionJudge(context: CyberVinciHostToolExecutionContext, prompt: string, reason: string): CyberVinciHostToolExecutionResult;
    protected createCanvasDiagnosticRepairOperations(document: OpenPencilDocument, diagnostics: CyberVinciCanvasDiagnostic[]): OpenPencilDesignOperation[];
    protected chooseOverlapRepairTarget(left: CyberVinciCanvasNodeBox | undefined, right: CyberVinciCanvasNodeBox | undefined): CyberVinciCanvasNodeBox | undefined;
    protected recordFromUnknown(value: unknown): Record<string, unknown> | undefined;
    protected coerceCanvasBox(value: CyberVinciCanvasNodeBox | Record<string, unknown> | undefined): CyberVinciCanvasNodeBox | undefined;
    protected createCanvasFooterOperation(document: OpenPencilDocument): OpenPencilDesignOperation;
    protected createCanvasCartOperation(document: OpenPencilDocument): OpenPencilDesignOperation;
    protected canvasDiagnosticRecommendation(diagnostic: CyberVinciCanvasDiagnostic): string;
    protected getCanvasSession(context: CyberVinciHostToolExecutionContext): {
        ok: true;
        session: OpenPencilDesignSession;
    } | CyberVinciHostToolExecutionResult;
    protected isCanvasSessionResult(candidate: {
        ok: true;
        session: OpenPencilDesignSession;
    } | CyberVinciHostToolExecutionResult): candidate is {
        ok: true;
        session: OpenPencilDesignSession;
    };
    protected getActiveCanvasWidgetUri(): URI | undefined;
    protected getActiveCanvasWidget(uri: URI): {
        node?: HTMLElement;
    } | undefined;
    protected readCanvasOperations(context: CyberVinciHostToolExecutionContext): OpenPencilDesignOperation[];
    protected readCanvasApplyOptions(context: CyberVinciHostToolExecutionContext): OpenPencilApplyOperationsOptions;
    protected computeCanvasDiagnostics(document: OpenPencilDocument, categories?: CyberVinciCanvasDiagnostic['category'][]): CyberVinciCanvasDiagnostic[];
    protected canvasValidationIssueToDiagnostic(issue: OpenPencilValidationIssue, category?: CyberVinciCanvasDiagnostic['category']): CyberVinciCanvasDiagnostic;
    protected detectCanvasOffCanvasNodes(boxes: CyberVinciCanvasNodeBox[], page: OpenPencilPage): CyberVinciCanvasDiagnostic[];
    protected detectCanvasOverlaps(boxes: CyberVinciCanvasNodeBox[]): CyberVinciCanvasDiagnostic[];
    protected detectCanvasTextOverflow(boxes: CyberVinciCanvasNodeBox[]): CyberVinciCanvasDiagnostic[];
    protected detectCanvasFooterPresence(boxes: CyberVinciCanvasNodeBox[], page: OpenPencilPage): CyberVinciCanvasDiagnostic[];
    protected detectCanvasCloneCompleteness(document: OpenPencilDocument, boxes: CyberVinciCanvasNodeBox[]): CyberVinciCanvasDiagnostic[];
    protected createResizeToFitOperations(document: OpenPencilDocument): OpenPencilDesignOperation[];
    protected getActiveCanvasPage(document: OpenPencilDocument): OpenPencilPage;
    protected summarizeCanvasDocument(document: OpenPencilDocument, page: OpenPencilPage): Record<string, unknown>;
    protected flattenCanvasBoxes(nodes: OpenPencilNode[] | undefined, parentId?: string, depth?: number): CyberVinciCanvasNodeBox[];
    protected numberValue(value: unknown, fallback: number): number;
    protected intersectionArea(left: CyberVinciCanvasNodeBox, right: CyberVinciCanvasNodeBox): number;
    protected isLikelyIntentionalOverlap(left: CyberVinciCanvasNodeBox, right: CyberVinciCanvasNodeBox): boolean;
    protected isCanvasStructuralContainerBox(box: CyberVinciCanvasNodeBox): boolean;
    protected estimatedTextHeight(text: string, width: number): number;
    protected cloneJson<T>(value: T): T;
    protected readResultRecord(result: CyberVinciHostToolExecutionResult): Record<string, unknown> | undefined;
    protected visionJudgeInputItems(context: CyberVinciHostToolExecutionContext, visualSnapshot: Record<string, unknown> | undefined): Promise<CodexProviderInputItem[]>;
    protected svgToPngDataUrl(svg: string, bounds: unknown): Promise<string | undefined>;
    protected readVisualSnapshotSize(bounds: unknown): {
        width: number;
        height: number;
    } | undefined;
    protected readVisionExecutionSelection(context: CyberVinciHostToolExecutionContext): CyberVinciAiExecutionSelection;
    protected readAiExecutionSelection(context: CyberVinciHostToolExecutionContext): CyberVinciAiExecutionSelection;
    protected readObjectInput<T>(value: unknown): Partial<T>;
    protected readFirstStringInput(input: Record<string, unknown>, keys: string[]): string | undefined;
    protected resolveToolArgs(args: Record<string, unknown>, context: CyberVinciHostToolExecutionContext): Record<string, unknown>;
    protected resolveToolValue(value: unknown, context: CyberVinciHostToolExecutionContext): unknown;
    protected lookupToolPath(pathExpression: string, context: CyberVinciHostToolExecutionContext): unknown;
    protected toFlowWorkflowSummaryForAi(workflow: FlowWorkflow): FlowWorkflowSummaryForAi;
    protected toLanguageModelOptions(providers: CyberVinciAiProviderDescriptor[]): Array<{
        id: string;
        label: string;
        status: 'ready' | 'unavailable';
    }>;
    protected coerceFlowAiAuthoringDraft(value: unknown): FlowAiAuthoringDraft;
    protected ensureToolPolicyApproved(tool: CyberVinciToolDefinition, context: CyberVinciHostToolExecutionContext): Promise<CyberVinciHostToolExecutionResult>;
    protected playbookToFlowWorkflow(playbook: CyberVinciPlaybookDefinition, prompt: string): FlowWorkflow;
    protected playbookStateToFlowStateType(type: string): FlowWorkflow['states'][string]['type'];
    protected playbookStatePrompt(state: Record<string, unknown>): string;
    protected playbookStateTransitions(state: Record<string, unknown>): Array<{
        to: string;
        on: string;
        guard?: string;
    }>;
    protected readNumberInput(value: unknown, fallback: number): number;
    protected readStringArray(value: unknown): string[] | undefined;
    protected readMemoryScope(value: unknown): MemoryScope;
    protected readMemoryType(value: unknown): MemoryItem['memoryType'];
    protected readMemoryTitle(input: Record<string, unknown>, content: string): string;
    protected executeSystemStub(toolId: string): CyberVinciHostToolExecutionResult;
    protected readWorkspaceRootUri(context: CyberVinciHostToolExecutionContext): string | undefined;
    protected resolveWorkspaceRootUri(context: CyberVinciHostToolExecutionContext): Promise<string | undefined>;
    protected resolveWorkspacePath(context: CyberVinciHostToolExecutionContext): Promise<string | undefined>;
}
export {};
