import { OpenerService, ReactWidget } from '@theia/core/lib/browser';
import { FrontendLanguageModelRegistry } from '@theia/ai-core';
import { CommandService } from '@theia/core/lib/common/command';
import { CyberVinciAiExecutionSelection, CyberVinciAiProviderDescriptor, CyberVinciAiRuntimeService } from '@cybervinci/ai-runtime/lib/common';
import * as React from '@theia/core/shared/react';
import { WorkspaceService } from '@theia/workspace/lib/browser';
import { FlowAiAuthoringDraft, FlowAgentMarkdownSummary, FlowMemoryScope, FlowModelProfile, FlowRun, FlowRunExecutionMode, FlowClient, FlowService, FlowSnapshot, FlowStateType, FlowValidationIssue, FlowWorkflow, FlowWorkflowStructuralDiff, FlowDeliverable, FlowPipelinePreset, FlowPatternRoleOverride, FlowWorkflowPattern, FlowWorkflowTemplate, FlowWorkflowTransition } from '../common';
interface FlowWidgetState {
    snapshot?: FlowSnapshot;
    templates: FlowWorkflowTemplate[];
    workflowPatterns: FlowWorkflowPattern[];
    modelProfiles: FlowModelProfile[];
    selectedModelProfileId?: string;
    modelProfileDraft?: FlowModelProfile;
    languageModels: FlowLanguageModelOption[];
    pipelinePresets: FlowPipelinePreset[];
    agents: FlowAgentMarkdownSummary[];
    agentSearch: string;
    selectedTemplateId?: string;
    selectedPatternId?: string;
    patternParameters: Record<string, string | number | boolean>;
    patternRoleOverrides: Record<string, FlowPatternRoleOverride>;
    selectedPipelinePresetId?: string;
    selectedKind: 'state' | 'transition';
    selectedId?: string;
    detailsPopoverOpen: boolean;
    detailsEditMode: boolean;
    workflowUndoStack: FlowWorkflowHistoryEntry[];
    workflowRedoStack: FlowWorkflowHistoryEntry[];
    workflowSourceText?: string;
    workflowSourceError?: string;
    workflowSourceVisible: boolean;
    workflowSavePreview?: FlowWorkflowStructuralDiff;
    selectedArtifactId?: string;
    runHistory: FlowRun[];
    runHistoryVisible: boolean;
    openMenu?: FlowTopMenu;
    prompt: string;
    aiMode: FlowAiInteractionMode;
    selectedAiWorkflowId?: string;
    aiPromptOpen: boolean;
    aiPrompt: string;
    aiExecution: CyberVinciAiExecutionSelection;
    aiQuestion?: string;
    aiAnswer?: string;
    busy: boolean;
    error?: string;
    executionModeHint?: FlowRunExecutionMode;
    executionModeHintMessage?: string;
}
interface FlowWorkflowHistoryEntry {
    workflow: FlowWorkflow;
    selectedKind: 'state' | 'transition';
    selectedId?: string;
}
type FlowTopMenu = 'workflow' | 'prompt' | 'file' | 'agents' | 'models' | 'kanban' | 'history';
type FlowAiInteractionMode = 'chat' | 'saved-flow' | 'dynamic-flow';
export interface FlowExternalRunOptions {
    prompt?: string;
    message?: string;
    input?: string;
    workflowId?: string;
    workspaceRootUri?: string;
    preferSaved?: boolean;
    parameters?: Record<string, unknown>;
    roleOverrides?: Record<string, FlowPatternRoleOverride>;
    authoringDraft?: FlowAiAuthoringDraft;
    draft?: FlowAiAuthoringDraft;
}
interface FlowLanguageModelOption {
    id: string;
    label: string;
    status: 'ready' | 'unavailable';
}
export declare class FlowWidget extends ReactWidget {
    static readonly ID = "flow.widget";
    static readonly LABEL = "Flow";
    protected readonly flowService: FlowService;
    protected readonly flowClient: FlowClient;
    protected readonly workspaceService: WorkspaceService;
    protected readonly languageModelRegistry: FrontendLanguageModelRegistry;
    protected readonly aiRuntime?: CyberVinciAiRuntimeService;
    protected readonly commandService: CommandService;
    protected readonly openerService: OpenerService;
    protected state: FlowWidgetState;
    protected activeRunStreamId?: string;
    protected readonly streamDisposers: Array<() => void>;
    protected init(): void;
    dispose(): void;
    protected registerRunStreamClient(): void;
    readonly refresh: () => Promise<void>;
    protected render(): React.ReactNode;
    protected setPrompt(prompt: string): void;
    protected setAiPrompt(aiPrompt: string): void;
    protected setAiExecution(aiExecution: CyberVinciAiExecutionSelection): void;
    protected setAiMode(aiMode: FlowAiInteractionMode): void;
    protected setSelectedAiWorkflow(selectedAiWorkflowId: string): void;
    protected readonly toggleAiPromptPanel: () => void;
    protected renderAiPromptPanel(): React.ReactNode;
    protected renderAiModeButton(mode: FlowAiInteractionMode, icon: string, label: string): React.ReactNode;
    protected readonly handleTopMenuPointerDown: (event: PointerEvent) => void;
    protected readonly handleTopMenuKeyDown: (event: KeyboardEvent) => void;
    protected readonly toggleTopMenu: (openMenu: FlowTopMenu) => void;
    protected closeTopMenus(): void;
    protected runMenuCommand(command: () => void | Promise<void>): Promise<void>;
    protected setSelectedTemplate(selectedTemplateId: string): void;
    protected setSelectedPipelinePreset(selectedPipelinePresetId: string): void;
    protected readonly setSelectedPattern: (selectedPatternId: string) => void;
    protected readonly setSelectedModelProfile: (selectedModelProfileId: string) => void;
    protected readonly updateModelProfileDraft: (patch: Partial<FlowModelProfile>) => void;
    protected readonly updateModelProfileExecutionDraft: (selection: CyberVinciAiExecutionSelection) => void;
    protected readonly saveModelProfileDraft: () => Promise<void>;
    protected readonly updatePatternParameter: (parameterId: string, value: string | number | boolean) => void;
    protected readonly updatePatternRoleOverride: (roleId: string, override: FlowPatternRoleOverride | undefined) => void;
    protected readonly setAgentSearch: (agentSearch: string) => void;
    protected readonly toggleWorkflowSourcePanel: () => void;
    protected readonly createAgentMarkdown: () => Promise<void>;
    protected readonly duplicateAgentMarkdown: (sourceRelativePath: string) => Promise<void>;
    protected readonly renameAgentMarkdown: (sourceRelativePath: string) => Promise<void>;
    protected select(selectedKind: 'state' | 'transition', selectedId: string): void;
    protected readonly openStateDetails: (selectedId: string) => void;
    protected readonly openTransitionDetails: (selectedId: string) => void;
    protected readonly startDetailsEdit: () => void;
    protected readonly exitDetailsEdit: () => void;
    protected readonly closeDetailsPopover: () => void;
    protected readonly saveWorkflowFileAndExitEdit: () => Promise<void>;
    protected readonly configureAiProvider: (provider: CyberVinciAiProviderDescriptor) => Promise<void>;
    protected readonly updateWorkflowSourceDraft: (workflowSourceText: string) => Promise<void>;
    protected readonly applyWorkflowSourceDraft: () => Promise<void>;
    protected readonly selectValidationIssue: (issue: FlowValidationIssue) => void;
    protected readonly addWorkflowState: (stateType: FlowStateType) => Promise<string | undefined>;
    protected readonly updateWorkflowState: (stateId: string, statePatch: Partial<FlowWorkflow["states"][string]>) => Promise<void>;
    protected readonly moveWorkflowState: (stateId: string, position: {
        x: number;
        y: number;
    }) => Promise<void>;
    protected readonly addParallelBranch: (parallelStateId: string, branchType: FlowStateType) => Promise<string | undefined>;
    protected readonly deleteWorkflowState: (stateId: string) => Promise<void>;
    protected readonly addWorkflowTransition: (from: string, to: string) => Promise<string | undefined>;
    protected readonly updateWorkflowTransition: (transitionId: string, transitionPatch: Partial<FlowWorkflowTransition>) => Promise<void>;
    protected readonly deleteWorkflowTransition: (transitionId: string) => Promise<void>;
    protected replaceActiveWorkflow(activeWorkflow: FlowWorkflow, selectedKind: 'state' | 'transition', selectedId?: string): Promise<void>;
    protected setActiveWorkflow(activeWorkflow: FlowWorkflow, selectedKind: 'state' | 'transition', selectedId: string | undefined, pushHistory: boolean): Promise<void>;
    protected readonly undoWorkflowEdit: () => Promise<void>;
    protected readonly redoWorkflowEdit: () => Promise<void>;
    runWorkflowFromExternalPrompt(options?: FlowExternalRunOptions): Promise<void>;
    runDynamicWorkflowFromExternalPrompt(options?: FlowExternalRunOptions): Promise<void>;
    protected applyExternalRunState(workspaceRootUri: string | undefined, workflowId: string, activeRun: FlowRun, prompt: string): Promise<void>;
    protected requireRunPrompt(value: string | undefined): string;
    protected readonly startRun: () => Promise<void>;
    protected readonly chooseWorkflow: (workflowId: string) => Promise<void>;
    protected readonly createWorkflowFromTemplate: () => Promise<void>;
    protected readonly reloadWorkflowFile: () => Promise<void>;
    protected readonly createWorkflowFromPreset: () => Promise<void>;
    protected readonly createWorkflowFromPattern: () => Promise<void>;
    protected readonly runWorkflowPattern: () => Promise<void>;
    protected readonly runFlowAiPrompt: () => Promise<void>;
    protected readonly runDynamicWorkflowFromPrompt: () => Promise<void>;
    protected readonly saveCurrentWorkflowAsPreset: () => Promise<void>;
    protected readonly openAgentMarkdown: (agentIdOrPath: string) => Promise<void>;
    protected readonly selectStateAgent: (stateId: string, selection: string) => Promise<void>;
    protected readonly openArtifact: (artifactUri: string) => Promise<void>;
    protected readonly selectArtifact: (artifactId: string) => void;
    protected readonly toggleRunHistory: () => Promise<void>;
    protected readonly openRunFromHistory: (runId: string) => Promise<void>;
    protected applyRunUpdate(run: FlowRun): void;
    protected readonly saveWorkflowFile: () => Promise<void>;
    protected readonly confirmSaveWorkflowFile: () => Promise<void>;
    protected readonly cancelSaveWorkflowPreview: () => void;
    protected readonly importWorkflow: () => Promise<void>;
    protected readonly importRun: () => Promise<void>;
    protected readonly exportWorkflow: () => Promise<void>;
    protected readonly exportRun: () => Promise<void>;
    protected readonly showWorkflowHistory: () => Promise<void>;
    protected readonly restoreWorkflowVersion: () => Promise<void>;
    protected writeWorkflowFile(workflow: FlowWorkflow, snapshot: FlowSnapshot, fallbackValidation: FlowSnapshot['validation']): Promise<void>;
    protected readonly tickRun: () => Promise<void>;
    protected readonly pauseRun: () => Promise<void>;
    protected readonly resumeRun: () => Promise<void>;
    protected readonly cancelRun: () => Promise<void>;
    protected readonly finalizeRun: () => Promise<void>;
    protected readonly cleanupActiveRun: () => Promise<void>;
    protected runLifecycleAction(action: 'pauseRun' | 'resumeRun' | 'cancelRun' | 'finalizeRun', reason: string): Promise<void>;
    protected readonly approveGate: (gateId: string, decision: "approved" | "rejected" | "revision_requested", decisionId?: string, targetStateId?: string, note?: string) => Promise<void>;
    protected readonly decideMemoryCandidate: (candidateId: string, decision: "approved" | "rejected", content: string, scope?: FlowMemoryScope, target?: string) => Promise<void>;
    protected readonly decideEffect: (effectId: string, decision: "approved" | "rejected" | "applied", note?: string) => Promise<void>;
    protected readonly approveSecondRunSuggestion: (suggestionId: string) => Promise<void>;
    protected readonly dismissSecondRunSuggestion: (suggestionId: string) => Promise<void>;
    protected withBusy(task: () => Promise<void>, onError?: (error: unknown) => {
        executionModeHint?: FlowRunExecutionMode;
        executionModeHintMessage?: string;
    } | undefined): Promise<void>;
    protected workspaceRootUri(): Promise<string | undefined>;
    protected workspaceRootPath(): Promise<string | undefined>;
    protected subscribeActiveRunStream(runId: string | undefined): Promise<void>;
    protected unsubscribeActiveRunStream(): Promise<void>;
}
export declare function textToDeliverables(value: string): FlowDeliverable[] | undefined;
export declare function deliverablesToText(value?: FlowDeliverable[]): string;
export {};
