import { CyberVinciAgent, CyberVinciAgentCatalog, CyberVinciAgentSummary, CyberVinciAgencyAgent, CyberVinciAgencyAgentSummary, CyberVinciAiChatExperienceClient, CyberVinciAiChatExperienceService, CyberVinciCatalogDiagnostic, CyberVinciCatalogItemKind, CyberVinciCatalogLocations, CyberVinciCatalogRestoreResult, CyberVinciCatalogWriteResult, CyberVinciMarketplaceCollection, CyberVinciMarketplaceItem, CyberVinciFrontendBridgeSmokeResult, CyberVinciDeclarativeChatAgent, CyberVinciDeclarativeChatAgentManifest, CyberVinciDeclarativeTool, CyberVinciDeclarativeToolExecutionResult, CyberVinciPlaybookDefinition, CyberVinciFlowPlaybookRunRequest, CyberVinciFlowPlaybookRunResult, CyberVinciRuntimeDiagnostics, CyberVinciPlaybookSummary, CyberVinciToolDefinition } from '../common';
import { CyberVinciCatalogValidator } from './cybervinci-catalog-validator';
declare const CATALOG_SOURCE_ORDER: readonly [{
    readonly directory: "system";
    readonly source: "system";
}, {
    readonly directory: "system-overrides";
    readonly source: "system-override";
}, {
    readonly directory: "user";
    readonly source: "user";
}];
type CatalogSource = typeof CATALOG_SOURCE_ORDER[number]['source'];
interface CatalogFragments {
    agents: CyberVinciDeclarativeChatAgent[];
    tools: CyberVinciToolDefinition[];
    playbooks: CyberVinciPlaybookDefinition[];
    diagnostics: CyberVinciCatalogDiagnostic[];
}
export declare class CyberVinciAgencyAgentService implements CyberVinciAiChatExperienceService {
    protected cachedRoot: string | undefined;
    protected cachedManifestPath: string | undefined;
    protected cachedCatalogRoot: string | undefined;
    protected client: CyberVinciAiChatExperienceClient | undefined;
    protected readonly validator: CyberVinciCatalogValidator;
    setClient(client: CyberVinciAiChatExperienceClient | undefined): void;
    hasFlowPlaybookClient(): boolean;
    runPlaybookFromFlowOnClient(request: CyberVinciFlowPlaybookRunRequest): Promise<CyberVinciFlowPlaybookRunResult | undefined>;
    getRuntimeDiagnostics(): Promise<CyberVinciRuntimeDiagnostics>;
    runFrontendBridgeSmoke(): Promise<CyberVinciFrontendBridgeSmokeResult>;
    listAgents(): Promise<CyberVinciAgentSummary[]>;
    readAgent(id: string): Promise<CyberVinciAgent | undefined>;
    getAgentProfilePath(id: string): Promise<CyberVinciCatalogWriteResult>;
    duplicateAgentProfileToUser(id: string): Promise<CyberVinciCatalogWriteResult>;
    getAgentCatalog(): Promise<CyberVinciAgentCatalog>;
    listTools(): Promise<CyberVinciToolDefinition[]>;
    listPlaybooks(): Promise<CyberVinciPlaybookSummary[]>;
    getPlaybook(id: string): Promise<CyberVinciPlaybookDefinition | undefined>;
    getCatalogDiagnostics(): Promise<CyberVinciCatalogDiagnostic[]>;
    getCatalogLocations(): Promise<CyberVinciCatalogLocations>;
    restoreSystemOverride(kind: CyberVinciCatalogItemKind, id: string): Promise<CyberVinciCatalogRestoreResult>;
    deleteUserCatalogItem(kind: CyberVinciCatalogItemKind, id: string): Promise<CyberVinciCatalogRestoreResult>;
    duplicateCatalogItemToUser(kind: CyberVinciCatalogItemKind, id: string): Promise<CyberVinciCatalogWriteResult>;
    createUserAgentCopy(agent: CyberVinciDeclarativeChatAgent): Promise<CyberVinciCatalogWriteResult>;
    createSystemOverride(kind: CyberVinciCatalogItemKind, id: string): Promise<CyberVinciCatalogWriteResult>;
    assignAgentDefaultPlaybook(agentId: string, playbookId: string): Promise<CyberVinciCatalogWriteResult>;
    listMarketplaceItems(): Promise<CyberVinciMarketplaceItem[]>;
    installMarketplaceItem(id: string): Promise<CyberVinciCatalogWriteResult>;
    listAgencyAgents(): Promise<CyberVinciAgencyAgentSummary[]>;
    readAgencyAgent(id: string): Promise<CyberVinciAgencyAgent | undefined>;
    protected resolveAgencyAgentFile(id: string): Promise<{
        root: string;
        summary: CyberVinciAgencyAgentSummary;
        absolutePath: string;
    } | undefined>;
    getDeclarativeChatAgentManifest(): Promise<CyberVinciDeclarativeChatAgentManifest>;
    executeDeclarativeTool(toolId: string, argsJson: string): Promise<CyberVinciDeclarativeToolExecutionResult>;
    protected withAgentDefaults(agent: CyberVinciDeclarativeChatAgent): CyberVinciDeclarativeChatAgent;
    protected shouldMergeCatalogFragment(kind: 'Agent' | 'Tool' | 'Playbook', item: {
        id: string;
        source?: string;
    }, existing: unknown, diagnostics: CyberVinciCatalogDiagnostic[]): boolean;
    protected validateCatalogReferences(agents: Map<string, CyberVinciDeclarativeChatAgent>, tools: Map<string, CyberVinciToolDefinition>, playbooks: Map<string, CyberVinciPlaybookDefinition>, diagnostics: CyberVinciCatalogDiagnostic[]): void;
    protected nativeAgentPlaybookId(agentId: string): string;
    protected readSummary(root: string, absolutePath: string): Promise<CyberVinciAgencyAgentSummary | undefined>;
    protected extractFrontmatter(content: string): {
        name?: string;
        description?: string;
    };
    protected cleanFrontmatterValue(value: string): string;
    protected extractTitle(content: string): string | undefined;
    protected extractDescription(content: string, title: string): string | undefined;
    protected stripFrontmatter(content: string): string;
    protected titleFromFileName(fileName: string): string;
    protected normalizeId(value: string): string;
    protected collectMarkdownFiles(root: string): Promise<string[]>;
    protected resolveAgencyAgentsRoot(): Promise<string | undefined>;
    protected readDeclarativeChatAgentManifest(): Promise<CyberVinciDeclarativeChatAgentManifest | undefined>;
    protected readCatalogFragments(): Promise<CatalogFragments>;
    protected resolveCatalogRoot(): Promise<string | undefined>;
    protected collectCatalogFiles(root: string): Promise<string[]>;
    protected readCatalogFile(file: string): Promise<unknown>;
    protected stringifyCatalogFile(file: string, value: unknown): string;
    protected catalogCollectionKey(kind: CyberVinciCatalogItemKind): 'agents' | 'tools' | 'playbooks';
    protected findCatalogItem(kind: CyberVinciCatalogItemKind, id: string): Promise<Record<string, unknown> | undefined>;
    protected readMarketplaceItems(): Promise<CyberVinciMarketplaceItem[]>;
    protected marketplaceRecords(parsed: unknown): Record<string, unknown>[];
    protected isMarketplaceRecord(record: Record<string, unknown>): boolean;
    protected toMarketplaceItem(record: Record<string, unknown>, sourcePath: string, index: number): CyberVinciMarketplaceItem | undefined;
    protected marketplaceCollection(value: unknown): CyberVinciMarketplaceCollection | undefined;
    protected isCatalogInstallTarget(kind: unknown): kind is CyberVinciCatalogItemKind;
    protected installNonCatalogMarketplaceItem(item: CyberVinciMarketplaceItem, target: NonNullable<CyberVinciMarketplaceItem['installTarget']>): Promise<CyberVinciCatalogWriteResult>;
    protected installedNonCatalogMarketplaceItemIds(): Promise<Set<string>>;
    protected withMarketplaceInstallAudit(item: CyberVinciMarketplaceItem, target: NonNullable<CyberVinciMarketplaceItem['installTarget']>, result: CyberVinciCatalogWriteResult): Promise<CyberVinciCatalogWriteResult>;
    protected writeMarketplaceInstallAudit(item: CyberVinciMarketplaceItem, target: NonNullable<CyberVinciMarketplaceItem['installTarget']>, result: CyberVinciCatalogWriteResult): Promise<string>;
    protected marketplaceInstallAuditRecords(parsed: unknown): Record<string, unknown>[];
    protected fileSha256(filePath: string): Promise<string>;
    protected valueSha256(value: unknown): string;
    protected stableJson(value: unknown): string;
    protected marketplaceInstallRecords(parsed: unknown): Record<string, unknown>[];
    protected nonCatalogMarketplaceCollectionKey(collection: CyberVinciMarketplaceCollection): 'skills' | 'flows' | 'canvas-qa-packs' | undefined;
    protected catalogMarketplaceItem(collection: CyberVinciMarketplaceCollection, kind: CyberVinciCatalogItemKind, id: string, name: string, description: string | undefined, tags: string[] | undefined, sourcePath: string | undefined, installedUserIds: Set<string>): CyberVinciMarketplaceItem;
    protected copyCatalogItemForUser(kind: CyberVinciCatalogItemKind, item: Record<string, unknown>): Record<string, unknown>;
    protected copyCatalogItemForSystemOverride(item: Record<string, unknown>): Record<string, unknown>;
    protected materializeEditableNativeAgentPlaybook(root: string, agentCopy: Record<string, unknown>, sourceAgent: Record<string, unknown>): Promise<string | undefined>;
    protected createEditableAutonomousNativeAgentPlaybook(playbookId: string, sourceAgentId: string, agentCopy: Record<string, unknown>, sourceAgent: Record<string, unknown>): Record<string, unknown>;
    protected assignPlaybookToAgentRecord(item: Record<string, unknown>, playbookId: string): Record<string, unknown>;
    protected sanitizeCatalogItem(item: Record<string, unknown>): Record<string, unknown>;
    protected userCopyId(kind: CyberVinciCatalogItemKind, id: string): string;
    protected uniqueCatalogId(kind: CyberVinciCatalogItemKind, preferredId: string): Promise<string>;
    protected safeCatalogId(id: string): string;
    protected safeCatalogFileName(id: string): string;
    protected uniqueMarkdownOutputPath(directory: string, baseName: string): Promise<string>;
    protected cloneCatalogValue<T>(value: T): T;
    protected removeCatalogOverride(parsed: unknown, key: 'agents' | 'tools' | 'playbooks', id: string): {
        changed: boolean;
        removeFile?: boolean;
        value?: unknown;
    };
    protected updateCatalogItemInParsed(parsed: unknown, key: 'agents' | 'tools' | 'playbooks', id: string, updater: (item: Record<string, unknown>) => Record<string, unknown>): {
        changed: boolean;
        value?: unknown;
    };
    protected recordLooksLikeCatalogKind(record: Record<string, unknown>, key: 'agents' | 'tools' | 'playbooks'): boolean;
    protected mergeCatalogObject(result: CatalogFragments, parsed: unknown, source: CatalogSource, sourcePath: string): void;
    protected resolveDeclarativeChatAgentsPath(): Promise<string | undefined>;
    protected isDeclarativeChatAgent(candidate: unknown): candidate is CyberVinciDeclarativeChatAgent;
    protected isDeclarativeTool(candidate: unknown): candidate is CyberVinciDeclarativeTool;
    protected isPlaybookDefinition(candidate: unknown): candidate is CyberVinciPlaybookDefinition;
    protected isRecord(candidate: unknown): candidate is Record<string, unknown>;
    protected isCatalogDiagnostic(candidate: unknown): candidate is CyberVinciCatalogDiagnostic;
    protected resolveConfiguredPath(configuredPath: string): string;
    protected validateCommandToolPathPolicy(toolId: string, cwd: string, allowedPaths: string[] | undefined, deniedPaths: string[] | undefined): void;
    protected pathContainsOrEquals(parent: string, child: string): boolean;
    protected parentCandidates(start: string): string[];
    protected packageConfigCandidates(): string[];
    protected pathExists(candidate: string): Promise<boolean>;
}
export {};
